[package]
name = "ais-agent-solana"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
ais-agent-core = { path = "../ais-agent-core" }
ais-agent-chain-shared = { path = "../ais-agent-chain-shared" }
async-trait.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
solana-client.workspace = true
base64 = "0.22"
thiserror.workspace = true
solana-sdk.workspace = true
